import type { Metadata } from "next";
import { Saira } from "next/font/google";
import "./globals.css";
import HeaderComponent from "./components/header_component/header_component";
import Providers from "./components/providers/providers";

const inter = Saira({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-primary-color`}>
        <Providers>
          <HeaderComponent />
          {children}
        </Providers>
      </body>
    </html>
  );
}
